@extends('layouts.tenant')
@section('title','Item Entry')
@section('content')
<div class="space-y-6" x-data="{ currentTab: 'item-entry', openModal: false }">
    <div class="bg-white p-6 rounded-2xl border border-gray-200 shadow-sm">
        <div x-show="currentTab === 'item-entry'" x-transition class="space-y-6">
            <div class="border-b border-gray-100 pb-4 mb-6">
                <h3 class="text-lg font-bold text-gray-800">Create New Master Item</h3>
                <p class="text-xs text-gray-500 mt-1">Register a new product or component into the global inventory database.</p>
            </div>
            
            <form action="{{ isset($item) ? route('tenant.inventory.item.update', $item->id) : route('tenant.inventory.item.store') }}" method="POST" class="space-y-6">
                @csrf

                @if(isset($item))
                    @method('PUT')
                @endif
                <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
                    <div class="md:col-span-2 space-y-1.5">
                        <label class="text-xs font-bold text-slate-700 uppercase tracking-wider">Item Name *</label>
                        <input type="text" 
                        name="name"
                        value="{{ $item->name ?? '' }}" 
                        required 
                        placeholder="e.g., Premium Denim Fabric / Mens Formal Shirt" 
                        class="w-full px-3.5 py-2 text-xs bg-white border border-slate-200 rounded-xl focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 text-slate-800 font-semibold">
                    </div>

                    <div class="space-y-1.5">
                        <label class="text-xs font-bold text-slate-700 uppercase tracking-wider">SKU / Item Code (Auto Generated)</label>
                        <input type="text" 
                            name="sku" 
                            value="{{ $item->sku ?? '' }}" 
                            readonly 
                            class="w-full px-3.5 py-2 text-xs bg-gray-50 border border-slate-200 rounded-xl text-slate-500 font-mono font-bold cursor-not-allowed select-none focus:outline-none focus:ring-0 focus:border-slate-200"
                            title="This identifier is automatically generated by the Master Pipeline.">
                    </div>
                </div>

                <div class="grid grid-cols-1 md:grid-cols-4 gap-6">
                    <div class="space-y-1.5">
                        <label class="text-xs font-bold text-slate-700 uppercase tracking-wider">Style No (Optional)</label>
                        <select name="style_id" required class="w-full px-3.5 py-2 text-xs bg-white border border-slate-200 rounded-xl focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 text-slate-800 font-semibold">
                            <option value="">-- Select Style --</option>
                            @foreach($styles as $style)
                                <option {{ ($item->style_id == $style->id ? "selected" : "" ) }} value="{{ $style->id }}">{{ $style->name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="space-y-1.5">
                        <label class="text-xs font-bold text-slate-700 uppercase tracking-wider">Fabric Specification</label>
                        <select name="fabric_code" required class="w-full px-3.5 py-2 text-xs bg-white border border-slate-200 rounded-xl focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 text-slate-800 font-semibold">
                            <option value="">-- Select Febric Spec --</option>
                            @foreach($fabSpec as $spec)
                                <option {{ ($item->fabric_spec_id == $spec->id ? "selected" : "" ) }} value="{{ $spec->id }}">{{ $spec->name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="space-y-1.5">
                        <label class="text-xs font-bold text-slate-700 uppercase tracking-wider">Color Context</label>
                        <select name="color" required class="w-full px-3.5 py-2 text-xs bg-white border border-slate-200 rounded-xl focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 text-slate-800 font-semibold">
                            <option value="">-- Select Color Context --</option>
                            @foreach($colorContexts as $colorContext)
                                <option {{ ($item->color_context_id == $colorContext->id ? "selected" : "" ) }} value="{{ $colorContext->id }}">{{ $colorContext->name }} - [{{ $colorContext->color_code }}]</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="space-y-1.5">
                        <label class="text-xs font-bold text-slate-700 uppercase tracking-wider">Brand Name</label>
                        <select name="brand" required class="w-full px-3.5 py-2 text-xs bg-white border border-slate-200 rounded-xl focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 text-slate-800 font-semibold">
                            <option value="">-- Select Brand --</option>
                            @foreach($brands as $brand)
                                <option {{ ($item->brand_id == $brand->id ? "selected" : "" ) }} value="{{ $brand->id }}">{{ $brand->name }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>

                <div class="grid grid-cols-1 md:grid-cols-4 gap-6">
                    <div class="space-y-1.5">
                        <label class="text-xs font-bold text-slate-700 uppercase tracking-wider">Category *</label>
                        <select name="category_id" required class="w-full px-3.5 py-2 text-xs bg-white border border-slate-200 rounded-xl focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 text-slate-800 font-semibold">
                            <option value="">-- Select Category --</option>
                            @foreach($categories as $category)
                                <option {{ ($item->category_id == $category->id ? "selected" : "" ) }} value="{{ $category->id }}">{{ $category->name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="space-y-1.5">
                        <label class="text-xs font-bold text-slate-700 uppercase tracking-wider">Unit of Measure (UOM) *</label>
                        <select name="unit_id" required class="w-full px-3.5 py-2 text-xs bg-white border border-slate-200 rounded-xl focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 text-slate-800 font-semibold">
                            <option value="">-- Select Unit --</option>
                            @foreach($units as $unit)
                                <option {{ ($item->unit_id == $unit->id ? "selected" : "" ) }} value="{{ $unit->id }}">{{ $unit->name }} ({{ $unit->short_name }})</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="space-y-1.5">
                        <label class="text-xs font-bold text-slate-700 uppercase tracking-wider">Base Purchase Price *</label>
                        <input type="number" value="{{ $item->purchase_price ?? '' }}" step="0.01" name="purchase_price" required placeholder="0.00" class="w-full px-3.5 py-2 text-xs bg-white border border-slate-200 rounded-xl focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 text-slate-800 font-mono">
                    </div>

                    <div class="space-y-1.5">
                        <label class="text-xs font-bold text-slate-700 uppercase tracking-wider">Target Retail Sale Price *</label>
                        <input type="number" value="{{ $item->sale_price ?? '' }}" step="0.01" name="sale_price" required placeholder="0.00" class="w-full px-3.5 py-2 text-xs bg-white border border-slate-200 rounded-xl focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 text-slate-800 font-mono">
                    </div>
                </div>

                <div class="flex justify-end items-center gap-3 pt-4 border-t border-slate-100">
                    <a href="{{ route('tenant.inventory.items.index') }}" class="px-4 py-2 text-xs font-bold text-slate-500 bg-slate-50 hover:bg-slate-100 rounded-xl transition">Cancel</a>
                    <button type="submit" class="px-5 py-2 text-xs font-bold text-white bg-indigo-600 hover:bg-indigo-700 rounded-xl shadow-xs transition">
                        Save Master Item
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection