<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Supported Countries List (ISO 3166-1 Alpha-2)
    |--------------------------------------------------------------------------
    */
    'list' => [
        'AF' => ['name' => 'Afghanistan', 'currency' => 'AFN', 'currency_symbol' => '؋', 'phone_code' => '+93', 'timezone' => 'Asia/Kabul'],
        'AX' => ['name' => 'Åland Islands', 'currency' => 'EUR', 'currency_symbol' => '€', 'phone_code' => '+358', 'timezone' => 'Europe/Mariehamn'],
        'AL' => ['name' => 'Albania', 'currency' => 'ALL', 'currency_symbol' => 'L', 'phone_code' => '+355', 'timezone' => 'Europe/Tirane'],
        'DZ' => ['name' => 'Algeria', 'currency' => 'DZD', 'currency_symbol' => 'د.ج', 'phone_code' => '+213', 'timezone' => 'Africa/Algiers'],
        'AS' => ['name' => 'American Samoa', 'currency' => 'USD', 'currency_symbol' => '$', 'phone_code' => '+1-684', 'timezone' => 'Pacific/Pago_Pago'],
        'AD' => ['name' => 'Andorra', 'currency' => 'EUR', 'currency_symbol' => '€', 'phone_code' => '+376', 'timezone' => 'Europe/Andorra'],
        'AO' => ['name' => 'Angola', 'currency' => 'AOA', 'currency_symbol' => 'Kz', 'phone_code' => '+244', 'timezone' => 'Africa/Luanda'],
        'AI' => ['name' => 'Anguilla', 'currency' => 'XCD', 'currency_symbol' => '$', 'phone_code' => '+1-264', 'timezone' => 'America/Anguilla'],
        'AQ' => ['name' => 'Antarctica', 'currency' => 'USD', 'currency_symbol' => '$', 'phone_code' => '+672', 'timezone' => 'Antarctica/McMurdo'],
        'AG' => ['name' => 'Antigua and Barbuda', 'currency' => 'XCD', 'currency_symbol' => '$', 'phone_code' => '+1-268', 'timezone' => 'America/Antigua'],
        'AR' => ['name' => 'Argentina', 'currency' => 'ARS', 'currency_symbol' => '$', 'phone_code' => '+54', 'timezone' => 'America/Argentina/Buenos_Aires'],
        'AM' => ['name' => 'Armenia', 'currency' => 'AMD', 'currency_symbol' => '֏', 'phone_code' => '+374', 'timezone' => 'Asia/Yerevan'],
        'AW' => ['name' => 'Aruba', 'currency' => 'AWG', 'currency_symbol' => 'ƒ', 'phone_code' => '+297', 'timezone' => 'America/Aruba'],
        'AU' => ['name' => 'Australia', 'currency' => 'AUD', 'currency_symbol' => '$', 'phone_code' => '+61', 'timezone' => 'Australia/Sydney'],
        'AT' => ['name' => 'Austria', 'currency' => 'EUR', 'currency_symbol' => '€', 'phone_code' => '+43', 'timezone' => 'Europe/Vienna'],
        'AZ' => ['name' => 'Azerbaijan', 'currency' => 'AZN', 'currency_symbol' => '₼', 'phone_code' => '+994', 'timezone' => 'Asia/Baku'],
        'BS' => ['name' => 'Bahamas', 'currency' => 'BSD', 'currency_symbol' => '$', 'phone_code' => '+1-242', 'timezone' => 'America/Nassau'],
        'BH' => ['name' => 'Bahrain', 'currency' => 'BHD', 'currency_symbol' => '.د.ب', 'phone_code' => '+973', 'timezone' => 'Asia/Bahrain'],
        'BD' => ['name' => 'Bangladesh', 'currency' => 'BDT', 'currency_symbol' => '৳', 'phone_code' => '+880', 'timezone' => 'Asia/Dhaka'],
        'BB' => ['name' => 'Barbados', 'currency' => 'BBD', 'currency_symbol' => '$', 'phone_code' => '+1-246', 'timezone' => 'America/Barbados'],
        'BY' => ['name' => 'Belarus', 'currency' => 'BYN', 'currency_symbol' => 'Br', 'phone_code' => '+375', 'timezone' => 'Europe/Minsk'],
        'BE' => ['name' => 'Belgium', 'currency' => 'EUR', 'currency_symbol' => '€', 'phone_code' => '+32', 'timezone' => 'Europe/Brussels'],
        'BZ' => ['name' => 'Belize', 'currency' => 'BZD', 'currency_symbol' => 'BZ$', 'phone_code' => '+501', 'timezone' => 'America/Belize'],
        'BJ' => ['name' => 'Benin', 'currency' => 'XOF', 'currency_symbol' => 'CFA', 'phone_code' => '+229', 'timezone' => 'Africa/Porto-Novo'],
        'BM' => ['name' => 'Bermuda', 'currency' => 'BMD', 'currency_symbol' => '$', 'phone_code' => '+1-441', 'timezone' => 'America/Bermuda'],
        'BT' => ['name' => 'Bhutan', 'currency' => 'BTN', 'currency_symbol' => 'Nu.', 'phone_code' => '+975', 'timezone' => 'Asia/Thimphu'],
        'BO' => ['name' => 'Bolivia', 'currency' => 'BOB', 'currency_symbol' => '$b', 'phone_code' => '+591', 'timezone' => 'America/La_Paz'],
        'BA' => ['name' => 'Bosnia and Herzegovina', 'currency' => 'BAM', 'currency_symbol' => 'KM', 'phone_code' => '+387', 'timezone' => 'Europe/Sarajevo'],
        'BW' => ['name' => 'Botswana', 'currency' => 'BWP', 'currency_symbol' => 'P', 'phone_code' => '+267', 'timezone' => 'Africa/Gaborone'],
        'BR' => ['name' => 'Brazil', 'currency' => 'BRL', 'currency_symbol' => 'R$', 'phone_code' => '+55', 'timezone' => 'America/Sao_Paulo'],
        'BN' => ['name' => 'Brunei', 'currency' => 'BND', 'currency_symbol' => '$', 'phone_code' => '+673', 'timezone' => 'Asia/Bandar_Seri_Begawan'],
        'BG' => ['name' => 'Bulgaria', 'currency' => 'BGN', 'currency_symbol' => 'лв', 'phone_code' => '+359', 'timezone' => 'Europe/Sofia'],
        'BF' => ['name' => 'Burkina Faso', 'currency' => 'XOF', 'currency_symbol' => 'CFA', 'phone_code' => '+226', 'timezone' => 'Africa/Ouagadougou'],
        'BI' => ['name' => 'Burundi', 'currency' => 'BIF', 'currency_symbol' => 'FBu', 'phone_code' => '+257', 'timezone' => 'Africa/Bujumbura'],
        'KH' => ['name' => 'Cambodia', 'currency' => 'KHR', 'currency_symbol' => '៛', 'phone_code' => '+855', 'timezone' => 'Asia/Phnom_Penh'],
        'CM' => ['name' => 'Cameroon', 'currency' => 'XAF', 'currency_symbol' => 'FCFA', 'phone_code' => '+237', 'timezone' => 'Africa/Douala'],
        'CA' => ['name' => 'Canada', 'currency' => 'CAD', 'currency_symbol' => '$', 'phone_code' => '+1', 'timezone' => 'America/Toronto'],
        'CV' => ['name' => 'Cape Verde', 'currency' => 'CVE', 'currency_symbol' => '$', 'phone_code' => '+238', 'timezone' => 'Atlantic/Cape_Verde'],
        'KY' => ['name' => 'Cayman Islands', 'currency' => 'KYD', 'currency_symbol' => '$', 'phone_code' => '+1-345', 'timezone' => 'America/Cayman'],
        'CF' => ['name' => 'Central African Republic', 'currency' => 'XAF', 'currency_symbol' => 'FCFA', 'phone_code' => '+236', 'timezone' => 'Africa/Bangui'],
        'TD' => ['name' => 'Chad', 'currency' => 'XAF', 'currency_symbol' => 'FCFA', 'phone_code' => '+235', 'timezone' => 'Africa/Ndjamena'],
        'CL' => ['name' => 'Chile', 'currency' => 'CLP', 'currency_symbol' => '$', 'phone_code' => '+56', 'timezone' => 'America/Santiago'],
        'CN' => ['name' => 'China', 'currency' => 'CNY', 'currency_symbol' => '¥', 'phone_code' => '+86', 'timezone' => 'Asia/Shanghai'],
        'CO' => ['name' => 'Colombia', 'currency' => 'COP', 'currency_symbol' => '$', 'phone_code' => '+57', 'timezone' => 'America/Bogota'],
        'KM' => ['name' => 'Comoros', 'currency' => 'KMF', 'currency_symbol' => 'CF', 'phone_code' => '+269', 'timezone' => 'Indian/Comoro'],
        'CG' => ['name' => 'Congo (Brazzaville)', 'currency' => 'XAF', 'currency_symbol' => 'FCFA', 'phone_code' => '+242', 'timezone' => 'Africa/Brazzaville'],
        'CD' => ['name' => 'Congo (Kinshasa)', 'currency' => 'CDF', 'currency_symbol' => 'FC', 'phone_code' => '+243', 'timezone' => 'Africa/Kinshasa'],
        'CR' => ['name' => 'Costa Rica', 'currency' => 'CRC', 'currency_symbol' => '₡', 'phone_code' => '+506', 'timezone' => 'America/Costa_Rica'],
        'CI' => ['name' => 'Ivory Coast', 'currency' => 'XOF', 'currency_symbol' => 'CFA', 'phone_code' => '+225', 'timezone' => 'Africa/Abidjan'],
        'HR' => ['name' => 'Croatia', 'currency' => 'EUR', 'currency_symbol' => '€', 'phone_code' => '+385', 'timezone' => 'Europe/Zagreb'],
        'CU' => ['name' => 'Cuba', 'currency' => 'CUP', 'currency_symbol' => '₱', 'phone_code' => '+53', 'timezone' => 'America/Havana'],
        'CY' => ['name' => 'Cyprus', 'currency' => 'EUR', 'currency_symbol' => '€', 'phone_code' => '+357', 'timezone' => 'Asia/Nicosia'],
        'CZ' => ['name' => 'Czechia', 'currency' => 'CZK', 'currency_symbol' => 'Kč', 'phone_code' => '+420', 'timezone' => 'Europe/Prague'],
        'DK' => ['name' => 'Denmark', 'currency' => 'DKK', 'currency_symbol' => 'kr', 'phone_code' => '+45', 'timezone' => 'Europe/Copenhagen'],
        'DJ' => ['name' => 'Djibouti', 'currency' => 'DJF', 'currency_symbol' => 'Fdj', 'phone_code' => '+253', 'timezone' => 'Africa/Djibouti'],
        'DM' => ['name' => 'Dominica', 'currency' => 'XCD', 'currency_symbol' => '$', 'phone_code' => '+1-767', 'timezone' => 'America/Dominica'],
        'DO' => ['name' => 'Dominican Republic', 'currency' => 'DOP', 'currency_symbol' => 'RD$', 'phone_code' => '+1-809', 'timezone' => 'America/Santo_Domingo'],
        'EC' => ['name' => 'Ecuador', 'currency' => 'USD', 'currency_symbol' => '$', 'phone_code' => '+593', 'timezone' => 'America/Guayaquil'],
        'EG' => ['name' => 'Egypt', 'currency' => 'EGP', 'currency_symbol' => '£', 'phone_code' => '+20', 'timezone' => 'Africa/Cairo'],
        'SV' => ['name' => 'El Salvador', 'currency' => 'USD', 'currency_symbol' => '$', 'phone_code' => '+503', 'timezone' => 'America/El_Salvador'],
        'GQ' => ['name' => 'Equatorial Guinea', 'currency' => 'XAF', 'currency_symbol' => 'FCFA', 'phone_code' => '+240', 'timezone' => 'Africa/Malabo'],
        'ER' => ['name' => 'Eritrea', 'currency' => 'ERN', 'currency_symbol' => 'Nfk', 'phone_code' => '+291', 'timezone' => 'Africa/Asmara'],
        'EE' => ['name' => 'Estonia', 'currency' => 'EUR', 'currency_symbol' => '€', 'phone_code' => '+372', 'timezone' => 'Europe/Tallinn'],
        'SZ' => ['name' => 'Eswatini', 'currency' => 'SZL', 'currency_symbol' => 'L', 'phone_code' => '+268', 'timezone' => 'Africa/Mbabane'],
        'ET' => ['name' => 'Ethiopia', 'currency' => 'ETB', 'currency_symbol' => 'Br', 'phone_code' => '+251', 'timezone' => 'Africa/Addis_Ababa'],
        'FJ' => ['name' => 'Fiji', 'currency' => 'FJD', 'currency_symbol' => '$', 'phone_code' => '+679', 'timezone' => 'Pacific/Fiji'],
        'FI' => ['name' => 'Finland', 'currency' => 'EUR', 'currency_symbol' => '€', 'phone_code' => '+358', 'timezone' => 'Europe/Helsinki'],
        'FR' => ['name' => 'France', 'currency' => 'EUR', 'currency_symbol' => '€', 'phone_code' => '+33', 'timezone' => 'Europe/Paris'],
        'GA' => ['name' => 'Gabon', 'currency' => 'XAF', 'currency_symbol' => 'FCFA', 'phone_code' => '+241', 'timezone' => 'Africa/Libreville'],
        'GM' => ['name' => 'Gambia', 'currency' => 'GMD', 'currency_symbol' => 'D', 'phone_code' => '+220', 'timezone' => 'Africa/Banjul'],
        'GE' => ['name' => 'Georgia', 'currency' => 'GEL', 'currency_symbol' => '₾', 'phone_code' => '+995', 'timezone' => 'Asia/Tbilisi'],
        'DE' => ['name' => 'Germany', 'currency' => 'EUR', 'currency_symbol' => '€', 'phone_code' => '+49', 'timezone' => 'Europe/Berlin'],
        'GH' => ['name' => 'Ghana', 'currency' => 'GHS', 'currency_symbol' => '¢', 'phone_code' => '+233', 'timezone' => 'Africa/Accra'],
        'GR' => ['name' => 'Greece', 'currency' => 'EUR', 'currency_symbol' => '€', 'phone_code' => '+30', 'timezone' => 'Europe/Athens'],
        'GD' => ['name' => 'Grenada', 'currency' => 'XCD', 'currency_symbol' => '$', 'phone_code' => '+1-473', 'timezone' => 'America/Grenada'],
        'GT' => ['name' => 'Guatemala', 'currency' => 'GTQ', 'currency_symbol' => 'Q', 'phone_code' => '+502', 'timezone' => 'America/Guatemala'],
        'GN' => ['name' => 'Guinea', 'currency' => 'GNF', 'currency_symbol' => 'FG', 'phone_code' => '+224', 'timezone' => 'Africa/Conakry'],
        'GW' => ['name' => 'Guinea-Bissau', 'currency' => 'XOF', 'currency_symbol' => 'CFA', 'phone_code' => '+245', 'timezone' => 'Africa/Bissau'],
        'GY' => ['name' => 'Guyana', 'currency' => 'GYD', 'currency_symbol' => '$', 'phone_code' => '+592', 'timezone' => 'America/Guyana'],
        'HT' => ['name' => 'Haiti', 'currency' => 'HTG', 'currency_symbol' => 'G', 'phone_code' => '+509', 'timezone' => 'America/Port-au-Prince'],
        'HN' => ['name' => 'Honduras', 'currency' => 'HNL', 'currency_symbol' => 'L', 'phone_code' => '+504', 'timezone' => 'America/Tegucigalpa'],
        'HK' => ['name' => 'Hong Kong', 'currency' => 'HKD', 'currency_symbol' => '$', 'phone_code' => '+852', 'timezone' => 'Asia/Hong_Kong'],
        'HU' => ['name' => 'Hungary', 'currency' => 'HUF', 'currency_symbol' => 'Ft', 'phone_code' => '+36', 'timezone' => 'Europe/Budapest'],
        'IS' => ['name' => 'Iceland', 'currency' => 'ISK', 'currency_symbol' => 'kr', 'phone_code' => '+354', 'timezone' => 'Europe/Reykjavik'],
        'IN' => ['name' => 'India', 'currency' => 'INR', 'currency_symbol' => '₹', 'phone_code' => '+91', 'timezone' => 'Asia/Kolkata'],
        'ID' => ['name' => 'Indonesia', 'currency' => 'IDR', 'currency_symbol' => 'Rp', 'phone_code' => '+62', 'timezone' => 'Asia/Jakarta'],
        'IR' => ['name' => 'Iran', 'currency' => 'IRR', 'currency_symbol' => '﷼', 'phone_code' => '+98', 'timezone' => 'Asia/Tehran'],
        'IQ' => ['name' => 'Iraq', 'currency' => 'IQD', 'currency_symbol' =>'ع.د', 'phone_code' => '+964', 'timezone' => 'Asia/Baghdad'],
        'IE' => ['name' => 'Ireland', 'currency' => 'EUR', 'currency_symbol' => '€', 'phone_code' => '+353', 'timezone' => 'Europe/Dublin'],
        'IL' => ['name' => 'Israel', 'currency' => 'ILS', 'currency_symbol' => '₪', 'phone_code' => '+972', 'timezone' => 'Asia/Jerusalem'],
        'IT' => ['name' => 'Italy', 'currency' => 'EUR', 'currency_symbol' => '€', 'phone_code' => '+39', 'timezone' => 'Europe/Rome'],
        'JM' => ['name' => 'Jamaica', 'currency' => 'JMD', 'currency_symbol' => 'J$', 'phone_code' => '+1-876', 'timezone' => 'America/Jamaica'],
        'JP' => ['name' => 'Japan', 'currency' => 'JPY', 'currency_symbol' => '¥', 'phone_code' => '+81', 'timezone' => 'Asia/Tokyo'],
        'JO' => ['name' => 'Jordan', 'currency' => 'JOD', 'currency_symbol' => 'د.ا', 'phone_code' => '+962', 'timezone' => 'Asia/Amman'],
        'KZ' => ['name' => 'Kazakhstan', 'currency' => 'KZT', 'currency_symbol' => '₸', 'phone_code' => '+7', 'timezone' => 'Asia/Almaty'],
        'KE' => ['name' => 'Kenya', 'currency' => 'KES', 'currency_symbol' => 'KSh', 'phone_code' => '+254', 'timezone' => 'Africa/Nairobi'],
        'KW' => ['name' => 'Kuwait', 'currency' => 'KWD', 'currency_symbol' => 'د.ك', 'phone_code' => '+965', 'timezone' => 'Asia/Kuwait'],
        'KG' => ['name' => 'Kyrgyzstan', 'currency' => 'KGS', 'currency_symbol' => 'لв', 'phone_code' => '+996', 'timezone' => 'Asia/Bishkek'],
        'LA' => ['name' => 'Laos', 'currency' => 'LAK', 'currency_symbol' => '₭', 'phone_code' => '+856', 'timezone' => 'Asia/Vientiane'],
        'LV' => ['name' => 'Latvia', 'currency' => 'EUR', 'currency_symbol' => '€', 'phone_code' => '+371', 'timezone' => 'Europe/Riga'],
        'LB' => ['name' => 'Lebanon', 'currency' => 'LBP', 'currency_symbol' => 'ل.ل', 'phone_code' => '+961', 'timezone' => 'Asia/Beirut'],
        'LY' => ['name' => 'Libya', 'currency' => 'LYD', 'currency_symbol' => 'ل.د', 'phone_code' => '+218', 'timezone' => 'Africa/Tripoli'],
        'LU' => ['name' => 'Luxembourg', 'currency' => 'EUR', 'currency_symbol' => '€', 'phone_code' => '+352', 'timezone' => 'Europe/Luxembourg'],
        'MY' => ['name' => 'Malaysia', 'currency' => 'MYR', 'currency_symbol' => 'RM', 'phone_code' => '+60', 'timezone' => 'Asia/Kuala_Lumpur'],
        'MV' => ['name' => 'Maldives', 'currency' => 'MVR', 'currency_symbol' => 'Rf', 'phone_code' => '+960', 'timezone' => 'Indian/Maldives'],
        'MX' => ['name' => 'Mexico', 'currency' => 'MXN', 'currency_symbol' => '$', 'phone_code' => '+52', 'timezone' => 'America/Mexico_City'],
        'MA' => ['name' => 'Morocco', 'currency' => 'MAD', 'currency_symbol' => 'د.م.', 'phone_code' => '+212', 'timezone' => 'Africa/Casablanca'],
        'MM' => ['name' => 'Myanmar', 'currency' => 'MMK', 'currency_symbol' => 'K', 'phone_code' => '+95', 'timezone' => 'Asia/Yangon'],
        'NP' => ['name' => 'Nepal', 'currency' => 'NPR', 'currency_symbol' => 'Rs', 'phone_code' => '+977', 'timezone' => 'Asia/Kathmandu'],
        'NL' => ['name' => 'Netherlands', 'currency' => 'EUR', 'currency_symbol' => '€', 'phone_code' => '+31', 'timezone' => 'Europe/Amsterdam'],
        'NZ' => ['name' => 'New Zealand', 'currency' => 'NZD', 'currency_symbol' => '$', 'phone_code' => '+64', 'timezone' => 'Pacific/Auckland'],
        'NG' => ['name' => 'Nigeria', 'currency' => 'NGN', 'currency_symbol' => '₦', 'phone_code' => '+234', 'timezone' => 'Africa/Lagos'],
        'NO' => ['name' => 'Norway', 'currency' => 'NOK', 'currency_symbol' => 'kr', 'phone_code' => '+47', 'timezone' => 'Europe/Oslo'],
        'OM' => ['name' => 'Oman', 'currency' => 'OMR', 'currency_symbol' => 'ر.ع.', 'phone_code' => '+968', 'timezone' => 'Asia/Muscat'],
        'PK' => ['name' => 'Pakistan', 'currency' => 'PKR', 'currency_symbol' => '₨', 'phone_code' => '+92', 'timezone' => 'Asia/Karachi'],
        'PS' => ['name' => 'Palestine', 'currency' => 'ILS', 'currency_symbol' => '₪', 'phone_code' => '+970', 'timezone' => 'Asia/Gaza'],
        'PH' => ['name' => 'Philippines', 'currency' => 'PHP', 'currency_symbol' => '₱', 'phone_code' => '+63', 'timezone' => 'Asia/Manila'],
        'PL' => ['name' => 'Poland', 'currency' => 'PLN', 'currency_symbol' => 'zł', 'phone_code' => '+48', 'timezone' => 'Europe/Warsaw'],
        'PT' => ['name' => 'Portugal', 'currency' => 'EUR', 'currency_symbol' => '€', 'phone_code' => '+351', 'timezone' => 'Europe/Lisbon'],
        'QA' => ['name' => 'Qatar', 'currency' => 'QAR', 'currency_symbol' => 'ر.ق', 'phone_code' => '+974', 'timezone' => 'Asia/Qatar'],
        'RO' => ['name' => 'Romania', 'currency' => 'RON', 'currency_symbol' => 'lei', 'phone_code' => '+40', 'timezone' => 'Europe/Bucharest'],
        'RU' => ['name' => 'Russia', 'currency' => 'RUB', 'currency_symbol' => '₽', 'phone_code' => '+7', 'timezone' => 'Europe/Moscow'],
        'SA' => ['name' => 'Saudi Arabia', 'currency' => 'SAR', 'currency_symbol' => 'ر.س', 'phone_code' => '+966', 'timezone' => 'Asia/Riyadh'],
        'SG' => ['name' => 'Singapore', 'currency' => 'SGD', 'currency_symbol' => '$', 'phone_code' => '+65', 'timezone' => 'Asia/Singapore'],
        'ZA' => ['name' => 'South Africa', 'currency' => 'ZAR', 'currency_symbol' => 'R', 'phone_code' => '+27', 'timezone' => 'Africa/Johannesburg'],
        'KR' => ['name' => 'South Korea', 'currency' => 'KRW', 'currency_symbol' => '₩', 'phone_code' => '+82', 'timezone' => 'Asia/Seoul'],
        'ES' => ['name' => 'Spain', 'currency' => 'EUR', 'currency_symbol' => '€', 'phone_code' => '+34', 'timezone' => 'Europe/Madrid'],
        'LK' => ['name' => 'Sri Lanka', 'currency' => 'LKR', 'currency_symbol' => 'Rs', 'phone_code' => '+94', 'timezone' => 'Asia/Colombo'],
        'CH' => ['name' => 'Switzerland', 'currency' => 'CHF', 'currency_symbol' => 'CHF', 'phone_code' => '+41', 'timezone' => 'Europe/Zurich'],
        'TH' => ['name' => 'Thailand', 'currency' => 'THB', 'currency_symbol' => '฿', 'phone_code' => '+66', 'timezone' => 'Asia/Bangkok'],
        'TR' => ['name' => 'Turkey', 'currency' => 'TRY', 'currency_symbol' => '₺', 'phone_code' => '+90', 'timezone' => 'Europe/Istanbul'],
        'AE' => ['name' => 'United Arab Emirates', 'currency' => 'AED', 'currency_symbol' => 'د.إ', 'phone_code' => '+971', 'timezone' => 'Asia/Dubai'],
        'GB' => ['name' => 'United Kingdom', 'currency' => 'GBP', 'currency_symbol' => '£', 'phone_code' => '+44', 'timezone' => 'Europe/London'],
        'US' => ['name' => 'United States', 'currency' => 'USD', 'currency_symbol' => '$', 'phone_code' => '+1', 'timezone' => 'America/New_York'],
        'VN' => ['name' => 'Vietnam', 'currency' => 'VND', 'currency_symbol' => '₫', 'phone_code' => '+84', 'timezone' => 'Asia/Ho_Chi_Minh'],
        'YE' => ['name' => 'Yemen', 'currency' => 'YER', 'currency_symbol' => '﷼', 'phone_code' => '+967', 'timezone' => 'Asia/Aden'],
        'ZW' => ['name' => 'Zimbabwe', 'currency' => 'ZWL', 'currency_symbol' => '$', 'phone_code' => '+263', 'timezone' => 'Africa/Harare'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Default Country Configuration
    |--------------------------------------------------------------------------
    */
    'default' => env('DEFAULT_COUNTRY', 'BD'),
];